// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/db-srv/proto/db/db.proto

/*
Package go_micro_srv_db_db is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/db-srv/proto/db/db.proto

It has these top-level messages:
	Database
	Record
	ReadRequest
	ReadResponse
	CreateRequest
	CreateResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
*/
package go_micro_srv_db_db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Database struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Table string `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
}

func (m *Database) Reset()                    { *m = Database{} }
func (m *Database) String() string            { return proto.CompactTextString(m) }
func (*Database) ProtoMessage()               {}
func (*Database) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Database) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Database) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type Record struct {
	Id       string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Created  int64             `protobuf:"varint,2,opt,name=created" json:"created,omitempty"`
	Updated  int64             `protobuf:"varint,3,opt,name=updated" json:"updated,omitempty"`
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Bytes    string            `protobuf:"bytes,5,opt,name=bytes" json:"bytes,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Record) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Record) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Record) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *Record) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Record) GetBytes() string {
	if m != nil {
		return m.Bytes
	}
	return ""
}

type ReadRequest struct {
	Database *Database `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Id       string    `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadRequest) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Record *Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadResponse) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type CreateRequest struct {
	Database *Database `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Record   *Record   `protobuf:"bytes,2,opt,name=record" json:"record,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateRequest) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *CreateRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type UpdateRequest struct {
	Database *Database `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Record   *Record   `protobuf:"bytes,2,opt,name=record" json:"record,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateRequest) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *UpdateRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type DeleteRequest struct {
	Database *Database `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Id       string    `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteRequest) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SearchRequest struct {
	Database *Database         `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limit    int64             `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset   int64             `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchRequest) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *SearchRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *SearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchResponse struct {
	Records []*Record `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SearchResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Database)(nil), "go.micro.srv.db.db.Database")
	proto.RegisterType((*Record)(nil), "go.micro.srv.db.db.Record")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.srv.db.db.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.srv.db.db.ReadResponse")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.db.db.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.db.db.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.srv.db.db.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.micro.srv.db.db.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.db.db.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.db.db.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.db.db.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.db.db.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DB service

type DBClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type dBClient struct {
	cc *grpc.ClientConn
}

func NewDBClient(cc *grpc.ClientConn) DBClient {
	return &dBClient{cc}
}

func (c *dBClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.db.db.DB/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.db.db.DB/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.db.db.DB/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.db.db.DB/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.db.db.DB/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DB service

type DBServer interface {
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterDBServer(s *grpc.Server, srv DBServer) {
	s.RegisterService(&_DB_serviceDesc, srv)
}

func _DB_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.db.db.DB/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.db.db.DB/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.db.db.DB/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.db.db.DB/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.db.db.DB/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.db.db.DB",
	HandlerType: (*DBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _DB_Read_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _DB_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DB_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DB_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _DB_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/micro/db-srv/proto/db/db.proto",
}

func init() { proto.RegisterFile("github.com/micro/db-srv/proto/db/db.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xdd, 0x24, 0xdd, 0x6c, 0x99, 0xd2, 0xaa, 0xb2, 0x10, 0x8a, 0x2a, 0x24, 0x4a, 0x4e, 0xe5,
	0x40, 0x22, 0x95, 0x3d, 0xac, 0xe0, 0xb6, 0x14, 0x2e, 0x2b, 0x0e, 0x04, 0x21, 0xc4, 0xd1, 0x8e,
	0xbd, 0xbb, 0x11, 0x4d, 0x53, 0x6c, 0xb7, 0x52, 0x0f, 0x1c, 0xf8, 0x10, 0x3e, 0x8f, 0xff, 0x40,
	0x19, 0x3b, 0x65, 0x53, 0xdc, 0x0a, 0xa9, 0x48, 0x7b, 0xf3, 0xc4, 0x33, 0x6f, 0x9e, 0x67, 0xde,
	0x53, 0xe0, 0xf9, 0x4d, 0xa1, 0x6f, 0x57, 0x2c, 0xc9, 0xab, 0x32, 0x2d, 0x8b, 0x5c, 0x56, 0x29,
	0x67, 0x2f, 0x94, 0x5c, 0xa7, 0x4b, 0x59, 0xe9, 0x3a, 0x48, 0x39, 0x4b, 0xf0, 0x4c, 0xc8, 0x4d,
	0x95, 0x60, 0x4a, 0xa2, 0xe4, 0x3a, 0xe1, 0x2c, 0xe1, 0x2c, 0x3e, 0x87, 0xee, 0x8c, 0x6a, 0xca,
	0xa8, 0x12, 0x84, 0x40, 0x67, 0x41, 0x4b, 0x11, 0x79, 0x63, 0x6f, 0xf2, 0x20, 0xc3, 0x33, 0x79,
	0x04, 0xa7, 0x9a, 0xb2, 0xb9, 0x88, 0x7c, 0xfc, 0x68, 0x82, 0xf8, 0x97, 0x07, 0x61, 0x26, 0xf2,
	0x4a, 0x72, 0x32, 0x00, 0xbf, 0xe0, 0xb6, 0xc4, 0x2f, 0x38, 0x89, 0xe0, 0x2c, 0x97, 0x82, 0x6a,
	0xc1, 0xb1, 0x24, 0xc8, 0x9a, 0xb0, 0xbe, 0x59, 0x2d, 0x39, 0xde, 0x04, 0xe6, 0xc6, 0x86, 0x64,
	0x06, 0xdd, 0x52, 0x68, 0xca, 0xa9, 0xa6, 0x51, 0x67, 0x1c, 0x4c, 0x7a, 0xd3, 0x49, 0xf2, 0x37,
	0xd7, 0xc4, 0x74, 0x4c, 0xde, 0xdb, 0xd4, 0xb7, 0x0b, 0x2d, 0x37, 0xd9, 0xb6, 0xb2, 0xa6, 0xca,
	0x36, 0x5a, 0xa8, 0xe8, 0xd4, 0x50, 0xc5, 0x60, 0xf4, 0x1a, 0xfa, 0xad, 0x02, 0x32, 0x84, 0xe0,
	0xab, 0xd8, 0x58, 0xc6, 0xf5, 0xb1, 0x2e, 0x5c, 0xd3, 0xf9, 0x6a, 0xfb, 0x46, 0x0c, 0x5e, 0xf9,
	0x17, 0x5e, 0xfc, 0x19, 0x7a, 0x99, 0xa0, 0x3c, 0x13, 0xdf, 0x56, 0x42, 0x69, 0x72, 0x01, 0x5d,
	0x6e, 0x87, 0x85, 0xf5, 0xbd, 0xe9, 0x13, 0x17, 0xcf, 0x66, 0xa0, 0xd9, 0x36, 0xdb, 0x4e, 0xc9,
	0x6f, 0xa6, 0x14, 0x5f, 0xc2, 0x43, 0x03, 0xac, 0x96, 0xd5, 0x42, 0x09, 0x32, 0x85, 0x50, 0xe2,
	0xeb, 0x2c, 0xee, 0x68, 0xff, 0xfb, 0x33, 0x9b, 0x19, 0x7f, 0x87, 0xfe, 0x1b, 0x1c, 0xed, 0xf1,
	0xf4, 0xfe, 0xb4, 0xf7, 0xff, 0xb9, 0xfd, 0x10, 0x06, 0x4d, 0x7b, 0xf3, 0x88, 0x9a, 0xd0, 0x27,
	0xdc, 0xe8, 0xbd, 0x11, 0x6a, 0xda, 0x5b, 0x42, 0x5f, 0xa0, 0x3f, 0x13, 0x73, 0xf1, 0x3f, 0x08,
	0xed, 0x2e, 0x70, 0x08, 0x83, 0x06, 0xda, 0x36, 0xfb, 0xe1, 0x43, 0xff, 0xa3, 0xa0, 0x32, 0xbf,
	0x3d, 0xbe, 0xdb, 0xd5, 0x1d, 0x43, 0xf8, 0x68, 0x88, 0xd4, 0x55, 0xd9, 0x6a, 0x77, 0xc8, 0x17,
	0xf3, 0xa2, 0x2c, 0xb4, 0x75, 0x9d, 0x09, 0xc8, 0x63, 0x08, 0xab, 0xeb, 0x6b, 0x25, 0x74, 0xd4,
	0xc1, 0xcf, 0x36, 0x3a, 0xce, 0x2f, 0xef, 0x60, 0xd0, 0x70, 0xb2, 0xc2, 0x3e, 0x87, 0x33, 0xb3,
	0x1e, 0x15, 0x79, 0xf8, 0x90, 0x43, 0x9b, 0x6c, 0x52, 0xa7, 0x3f, 0x03, 0xf0, 0x67, 0x97, 0xe4,
	0x0a, 0x3a, 0xb5, 0x4b, 0xc8, 0x53, 0x77, 0xcd, 0xd6, 0x98, 0xa3, 0xf1, 0xfe, 0x04, 0xbb, 0x9d,
	0x13, 0xf2, 0x01, 0x42, 0xa3, 0x57, 0xf2, 0xcc, 0x95, 0xdd, 0xb2, 0xd2, 0x28, 0x3e, 0x94, 0x72,
	0x17, 0xd2, 0x28, 0xce, 0x0d, 0xd9, 0x32, 0x83, 0x1b, 0x72, 0x47, 0xb0, 0x08, 0x69, 0x74, 0xe5,
	0x86, 0x6c, 0xc9, 0xd9, 0x0d, 0xb9, 0x23, 0x4b, 0x84, 0x34, 0x4b, 0x71, 0x43, 0xb6, 0x44, 0xe4,
	0x86, 0x6c, 0xef, 0x34, 0x3e, 0x61, 0x21, 0xfe, 0x50, 0x5e, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x54, 0x4e, 0xd9, 0x89, 0x7d, 0x06, 0x00, 0x00,
}
