// Code generated by protoc-gen-go.
// source: github.com/micro/db-srv/proto/db/db.proto
// DO NOT EDIT!

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/db-srv/proto/db/db.proto

It has these top-level messages:
	Database
	Record
	ReadRequest
	ReadResponse
	CreateRequest
	CreateResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Database struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Table string `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
}

func (m *Database) Reset()                    { *m = Database{} }
func (m *Database) String() string            { return proto.CompactTextString(m) }
func (*Database) ProtoMessage()               {}
func (*Database) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Record struct {
	Id       string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Created  int64             `protobuf:"varint,2,opt,name=created" json:"created,omitempty"`
	Updated  int64             `protobuf:"varint,3,opt,name=updated" json:"updated,omitempty"`
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Bytes    string            `protobuf:"bytes,5,opt,name=bytes" json:"bytes,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Record) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ReadRequest struct {
	Database *Database `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Id       string    `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadRequest) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

type ReadResponse struct {
	Record *Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadResponse) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type CreateRequest struct {
	Database *Database `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Record   *Record   `protobuf:"bytes,2,opt,name=record" json:"record,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateRequest) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *CreateRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type UpdateRequest struct {
	Database *Database `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Record   *Record   `protobuf:"bytes,2,opt,name=record" json:"record,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateRequest) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *UpdateRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type DeleteRequest struct {
	Database *Database `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Id       string    `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteRequest) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SearchRequest struct {
	Database *Database         `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limit    int64             `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset   int64             `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchRequest) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *SearchRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SearchResponse struct {
	Records []*Record `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SearchResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Database)(nil), "Database")
	proto.RegisterType((*Record)(nil), "Record")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DB service

type DBClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type dBClient struct {
	c           client.Client
	serviceName string
}

func NewDBClient(serviceName string, c client.Client) DBClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "db"
	}
	return &dBClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *dBClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DB service

type DBHandler interface {
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterDBHandler(s server.Server, hdlr DBHandler) {
	s.Handle(s.NewHandler(&DB{hdlr}))
}

type DB struct {
	DBHandler
}

func (h *DB) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.DBHandler.Read(ctx, in, out)
}

func (h *DB) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.DBHandler.Create(ctx, in, out)
}

func (h *DB) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.DBHandler.Update(ctx, in, out)
}

func (h *DB) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.DBHandler.Delete(ctx, in, out)
}

func (h *DB) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.DBHandler.Search(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x5d, 0x92, 0x2e, 0xdd, 0x6e, 0x9a, 0x0c, 0x59, 0x42, 0x44, 0x85, 0x87, 0x29, 0x12, 0xda,
	0x00, 0xe1, 0x48, 0x45, 0x42, 0x13, 0x8f, 0xd0, 0x3d, 0xf2, 0x52, 0xc4, 0x07, 0x38, 0xc9, 0x1d,
	0x8d, 0x48, 0x9a, 0xe2, 0x38, 0x95, 0xfa, 0x35, 0xfc, 0x00, 0xff, 0xc4, 0xaf, 0xe0, 0xd8, 0x0e,
	0x8d, 0xcb, 0x4b, 0xd1, 0xa4, 0x3e, 0xd4, 0xd7, 0xe7, 0x9e, 0xeb, 0x73, 0xcf, 0x09, 0xbc, 0xfa,
	0x56, 0x8a, 0x75, 0x97, 0xd1, 0xbc, 0xa9, 0xd3, 0xba, 0xcc, 0x79, 0x93, 0x16, 0xd9, 0xdb, 0x96,
	0xef, 0xd2, 0x2d, 0x6f, 0x44, 0x7f, 0x90, 0x3f, 0xaa, 0xfe, 0x27, 0x37, 0x70, 0xb1, 0x64, 0x82,
	0x65, 0xac, 0x45, 0x32, 0x83, 0xc9, 0x86, 0xd5, 0x18, 0x3b, 0xd7, 0xce, 0xed, 0x25, 0x09, 0xe1,
	0x5c, 0xd6, 0x2b, 0x8c, 0xdd, 0xfe, 0x98, 0xfc, 0x74, 0xc0, 0x5f, 0x61, 0xde, 0xf0, 0x82, 0x00,
	0xb8, 0x65, 0x61, 0x50, 0x57, 0x30, 0xcd, 0x39, 0x32, 0x81, 0x85, 0xc2, 0x79, 0x7d, 0xa1, 0xdb,
	0x16, 0xaa, 0xe0, 0xa9, 0x82, 0x9c, 0x50, 0xa3, 0x60, 0xb2, 0xc4, 0xe2, 0xc9, 0xb5, 0x77, 0x1b,
	0x2c, 0x9e, 0x52, 0x4d, 0x44, 0x3f, 0x9b, 0xfa, 0xfd, 0x46, 0xf0, 0x7d, 0x3f, 0x30, 0xdb, 0x0b,
	0x6c, 0xe3, 0xf3, 0x9e, 0x79, 0x9e, 0x42, 0x68, 0xdf, 0x07, 0xe0, 0x7d, 0xc7, 0xfd, 0xe1, 0x75,
	0x3b, 0x56, 0x75, 0xe6, 0x75, 0x1f, 0xdc, 0x3b, 0x27, 0x79, 0x0f, 0xc1, 0x0a, 0x59, 0xb1, 0xc2,
	0x1f, 0x1d, 0xb6, 0x82, 0x3c, 0x87, 0x8b, 0xc2, 0x28, 0x53, 0x3d, 0xc1, 0xe2, 0x92, 0xfe, 0x95,
	0xaa, 0x25, 0x68, 0x65, 0x37, 0x30, 0xd3, 0x7d, 0xed, 0xb6, 0xd9, 0xc8, 0xbb, 0x67, 0xe0, 0x73,
	0xf5, 0x3e, 0xd3, 0x36, 0x35, 0xcf, 0x4d, 0xee, 0x21, 0xfc, 0xa4, 0xb4, 0x9e, 0x34, 0xe2, 0x40,
	0xe3, 0xda, 0x34, 0x4f, 0x20, 0x1a, 0x68, 0xf4, 0xc4, 0x9e, 0xf8, 0xab, 0xda, 0xd9, 0xa3, 0x89,
	0x07, 0x1a, 0x43, 0x7c, 0x07, 0xe1, 0x12, 0x2b, 0x3c, 0x91, 0x78, 0xbc, 0x14, 0xc9, 0x35, 0x74,
	0x1a, 0xae, 0x5f, 0x0e, 0x84, 0x5f, 0x90, 0xf1, 0x7c, 0x7d, 0x12, 0x19, 0x1d, 0xd9, 0xee, 0x2a,
	0xdb, 0x5f, 0x50, 0xab, 0xfd, 0x5f, 0xf7, 0xab, 0xb2, 0x2e, 0x85, 0x49, 0x4d, 0x04, 0x7e, 0xf3,
	0xf0, 0xd0, 0xa2, 0x90, 0x99, 0x91, 0xe7, 0xff, 0x4f, 0xc3, 0x6b, 0x88, 0x86, 0x71, 0xc6, 0xd7,
	0x18, 0xa6, 0x7a, 0x6f, 0xad, 0xec, 0xf2, 0x46, 0x8b, 0x5b, 0xfc, 0x76, 0xc0, 0x5d, 0x7e, 0x24,
	0x2f, 0x61, 0xd2, 0x07, 0x81, 0xcc, 0xe8, 0x28, 0x47, 0xf3, 0x90, 0x8e, 0xd3, 0x91, 0x9c, 0x91,
	0x37, 0xe0, 0x6b, 0xff, 0x48, 0x44, 0xad, 0x3c, 0xcc, 0xaf, 0xe8, 0x91, 0xb1, 0x0a, 0xac, 0x3d,
	0x91, 0x60, 0xcb, 0x63, 0x09, 0x3e, 0x32, 0x4b, 0x81, 0xf5, 0xd2, 0x25, 0xd8, 0xf2, 0x4d, 0x82,
	0x8f, 0xdc, 0x50, 0x60, 0x2d, 0x50, 0x82, 0xad, 0xc5, 0x4a, 0xb0, 0xad, 0x3c, 0x39, 0xcb, 0x7c,
	0xf5, 0xb5, 0xbf, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0xde, 0x30, 0xad, 0xdf, 0x1a, 0x04, 0x00,
	0x00,
}
